### PR TITLE
unit test

### PR DESCRIPTION
**Pull request by kunalbhatia18**
added files via upload include unit test files

### CODE REVIEW

**Review by malithsen — APPROVED** [review]

**Review by malithsen — COMMENTED** [review]
Please update the PR description

**Comment by ivantha** [comment]
@kunalbhatia18 Please remove the unnecessary **.js** file in the root and also the **.snap** file which is in  dronesym-node/tests. 
Also please refer to the Codacy results to fix the code quality issues.

**Comment by kunalbhatia18** [comment]
> @kunalbhatia18 Please remove the unnecessary **.js** file in the root and also the **.snap** file which is in dronesym-node/tests.
> Also please refer to the Codacy results to fix the code quality issues.

ok sir I will do it right now

**Comment by ivantha** [comment]
Please check, 
- .js file in the root
- Codacy results

**Comment by kunalbhatia18** [comment]
> Please check,
> 
> * .js file in the root
> * Codacy results

I am sorry for the problem but for this PR only files which are required are unit_test.js which is in the commit 'added files via upload', and the other commits are for end to end test. sorry for inconvenience
@OshanIvantha

**Comment by dilinade** [comment]
Similar tests have been added when resolving #292 and PR #319.

**Pull request closed without merging**
