### PR TITLE
Fixed : Issues while setting up

### PR DESCRIPTION
**Pull request by AdhyanDhull**
Fixed small errors faced while setting up DroneSym, 

Description for each provided in respective commits

### CODE REVIEW

**Comment by iammosespaulr** [comment]
These Changes are not Issues you would face when setting up dronesym in python2 .. this is specific for python3 btw "The import from Queue fix " is a positive pull request :+1:

**Comment by ivantha** [comment]
Most of these changes are included in #120 . But the additions to the README file would still be an improvement to the project. 
@AdhyanDhull  Can you please rebase this so that we can merge the remaining changes? 🙂

**Comment by dilinade** [comment]
@ivantha Issues that are addressed by this PR has been automatically solved with the integration to python 3.

**Comment by ivantha** [comment]
> @ivantha Issues that are addressed by this PR has been automatically solved with the integration to python 3.

I am closing this PR.

**Pull request closed without merging**
