### PR TITLE
Update README with firebase instructions and replace database filename

### LINKED ISSUE #111: change README for db.js, Provide Firebase instructions
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

* To find and edit `db.js` in `DroneSym/dronesym-node` folder.

# Current Behavior

* `db.js` is replaced in the repo by `example.db.js`. The `README` should be updated to highlight the change because new users may not be able to understand the change.
No db.js

* Most users have not used `FirebaseAdminSDK` previously before so documentation has to be provided to help new users to setup their `firebase key file` and `database url`.
## Suggestion-
* The instructions at [FireBaseSetup](https://firebase.google.com/docs/admin/setup#add_firebase_to_your_app) have to explained in a basic manner in the `README`/project wiki.

### PR DESCRIPTION
**Pull request by anuragparida**
Provided Easy to follow Firebase Setup instructions for new users as the official documentation might seem overcrowded for beginners.

Previous link for following instructions-

Crowded Firebase Documentation

New instructions-

New Documentation

Changed the line where database file was referred to as `db.js`. Now it correctly says `example.db.js`.

I have embedded screenshots to make it easy to follow the instructions. If required, the images can be removed from the end to follow the style structure of the rest of the README file.

closes #111

### CODE REVIEW

**Comment by anuragparida** [comment]
@OshanIvantha Please review :slightly_smiling_face:

**Review by swatisingh45 — COMMENTED** [review]
LGTM!

**Comment by ivantha** [comment]
@anuragparida I understand the value addition of a clear guide to the new users/devs of DroneSym. However as Firebase is a 3rd party service which is not related with SCoRe, we would need to update the README every time they change the interface. 
So it is advisable to provide a url to the Firebase's own guide for creating a key file.

**Comment by anuragparida** [comment]
I understand @OshanIvantha :) Should I change the PR to highlight the important points (Create URL and Key from <link>Console</link> and paste it in in document in the given fashion)? It will leave majority of the work to be seen from Firebase Instructions URL but because there are a lot of cluttered instructions there, this will simplify the process.

**Comment by ivantha** [comment]
@anuragparida If you still think there are doubtful/unclear instructions, you are welcome to change the PR 🙂

**Pull request closed without merging**
