### PR TITLE
End to End test- Drone management frontend

### PR DESCRIPTION
**Pull request by kunalbhatia18**
This includes the testing for the frontend part of the dronesym repo.

✔️ First, Check if the Drone has compatibility with the device you want to handle the drone with. It can be done by plugging and connecting the Drone with the device. If the device recognizes the Drone, then it's compatible, otherwise, it's not.

When connecting it to your machine and testing its Push Notification, it shows the results.
✔️ Then run the given Tests. The test case should get passed and protractor name should also be displayed.
testing-protractor-in-terminal

screen shot 2018-12-08 at 11 19 03 am

### CODE REVIEW

**Comment by ivantha** [comment]
@kunalbhatia18 Can you please clarify the changes that were done to the drone-list.component.ts file?

**Comment by kunalbhatia18** [comment]
> @kunalbhatia18 Can you please clarify the changes that were done to the drone-list.component.ts file?

@OshanIvantha (drone-list.component.ts)
not any particular changes just minor fixes which would run the test

**Comment by ivantha** [comment]
@kunalbhatia18 It is not _usually_ a correct practice to change the code so that it will run the tests. 
Can you elaborate the changes that you did please?

**Comment by kunalbhatia18** [comment]
> @kunalbhatia18 It is not _usually_ a correct practice to change the code so that it will run the tests.
> Can you elaborate the changes that you did please?

sorry I will keep that in mind, the changes i have done is from line 67-80.
it is just for dialog confirmation.
@OshanIvantha

**Comment by dilinade** [comment]
Files have been changed since the last update. I guess this won't be useful.

**Comment by dilinade** [comment]
Files have been changed since the last update. I guess this won't be useful. Closing PR #161

**Pull request closed without merging**
