### PR TITLE
Added user control tests

### PR DESCRIPTION
**Pull request by bauripalash**
Added UserCtrl Tests

>[removing merge conflicts]

### CODE REVIEW

**Review by SanyamPunia — APPROVED** [review]

**Comment by dilinade** [comment]
Seems the unit test is all good!

**Comment by ivantha** [comment]
@bauripalash Can you please rebase the PR so that we can get this merged?

**Comment by dilinade** [comment]
@ivantha Now these test are already there. Seems like need no merging.
image

**Comment by ivantha** [comment]
> @ivantha Now these test are already there. Seems like need no merging.
> image

I am closing this PR because the feature already exists.

**Pull request closed without merging**
