### PR TITLE
Update README with firebase instructions

### LINKED ISSUE #111: change README for db.js, Provide Firebase instructions
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

* To find and edit `db.js` in `DroneSym/dronesym-node` folder.

# Current Behavior

* `db.js` is replaced in the repo by `example.db.js`. The `README` should be updated to highlight the change because new users may not be able to understand the change.
No db.js

* Most users have not used `FirebaseAdminSDK` previously before so documentation has to be provided to help new users to setup their `firebase key file` and `database url`.
## Suggestion-
* The instructions at [FireBaseSetup](https://firebase.google.com/docs/admin/setup#add_firebase_to_your_app) have to explained in a basic manner in the `README`/project wiki.

### PR DESCRIPTION
**Pull request by anuragparida**
Provided Easy to follow Firebase Setup instructions for new users as the official documentation might seem overcrowded for beginners. Changed previous PR and provided more "vague" approach so that user can navigate the process even if firebase interface is changed. :smile: @OshanIvantha 

closes #111

### CODE REVIEW

**Review by ivantha — CHANGES_REQUESTED** [review]
Good job @anuragparida! 😃
But let's remove those screenshots. It kind of takes the focus away from the important stuff.

**Comment by ivantha** [comment]
References #152

**Comment by anuragparida** [comment]
@OshanIvantha Removed all the screenshots, and cropped the last screenshot just because it shows how to edit the document and what the links should look like.


GG

**Review by ivantha — APPROVED** [review]

**Comment by ivantha** [comment]
Closes #117

**Pull request merged**
